### ISSUE TITLE
Controller tries to scale above `maxReplicas` and gets stuck

### ISSUE THREAD

**Issue by grassator** [zalando-incubator/stackset-controller#110]
Currently stackset may decide to pre-scale the deployment to a number of pods higher than what is specified inside `maxReplicas`. Since HPA can not go beyond `maxReplicas` stackset continues waiting and never completes the switch.

Proposed change is to cap the prescaling based on `maxReplicas`

**Comment by mikkeloscar** [comment]
> Proposed change is to cap the prescaling based on maxReplicas

:+1:
