### ISSUE TITLE
Add support for other ingress controller

### ISSUE THREAD

**Issue by arjunrn** [zalando-incubator/stackset-controller#113]
Current the controller is tied to _Skipper_ as an ingress controller and the dependency is for the traffic switching annotation. The controller should support other ingress providers as well such like _Traefik_ which works exactly the same as skipper with the annotation `traefik.ingress.kubernetes.io/service-weights`. _Nginx_ behaves a little differently because it doesn't define the multiple backends on the same ingress but allows multiple ingresses with the same host.

**Comment by szuecs** [comment]
Traefik already agreed on using ours

**Comment by szuecs** [comment]
I think with https://github.com/zalando-incubator/stackset-controller/releases/tag/v1.1.0 we enable anyone to create whatever resource to build the LB infrastructure.

**Comment by szuecs** [comment]
I thought about it again and realized, that we could pass the annotation name via flag, default to `zalando.org/backend-weights`, which should fix the issue much better.
