### ISSUE TITLE
Apply application label metadata to podTemplate

### ISSUE THREAD

**Issue by macedigital** [zalando-incubator/stackset-controller#132]
**Description:**

Prior to kubernetes-training/pull/32, when using the provided stackset-template as-is, CDP builds will complain about missing application-labels, even though one is provided on the `StackSet`-level (see screenshot):

![pod-template-warning](https://user-images.githubusercontent.com/248495/57789971-2c817180-773a-11e9-9eff-efdfea04aaa1.png)

**Expected behavior:**

Metadata (application) labels should be inherited by the stackTemplate's podTemplate without the need for manual additions (or the example should include said change, see PR mentioned earlier).

**Actual Behavior:**

A user has to apply this patch to the `stackset.yaml` file in order to make the warning go away.

```diff
diff --git a/deploy/apply/stackset.yaml b/deploy/apply/stackset.yaml
index fbbf351..a3fe84d 100644
--- a/deploy/apply/stackset.yaml
+++ b/deploy/apply/stackset.yaml
@@ -19,6 +19,9 @@ spec:
       replicas: {{{REPLICAS}}}
       # full Pod template.
       podTemplate:
+        metadata:
+          labels:
+            application: "{{{APPLICATION}}}"
         spec:
           containers:
           - name: "{{{APPLICATION}}}"
```

**Comment by mikkeloscar** [comment]
Hi, the controller does the right thing, but the status reporting is wrong. We will fix the status reporting.
