### ISSUE TITLE
Unbounded Traffic Switch leads to slow actual switch and high number of pods

### ISSUE THREAD

**Issue by jeremycolin** [zalando-incubator/stackset-controller#134]
### Situation before traffic switching

We have 2 stacks running: 
- rendering-engine-master-356 with 75 pods and 90% traffic
- rendering-engine-master-358 with 75 pods and 10% traffic

![Screenshot 2019-05-28 at 13 26 28](https://user-images.githubusercontent.com/3767697/58474717-39479180-814c-11e9-908e-6576038e932e.png)

We realised an issue on rendering-engine-master-358 so we wanted to revert back to rendering-engine-master-356.

### Switching traffic back

`zkubectl traffic rendering-engine rendering-engine-master-356 100`

![Screenshot 2019-05-28 at 13 30 01](https://user-images.githubusercontent.com/3767697/58474886-b6730680-814c-11e9-9b6e-dd04ed39a8e5.png)

### Problem

Stack rendering-engine-master-356 was prescaled again - but to a very high number of pods: 250 which is much more than the sum of all the pods handling traffic before traffic switch (75+75=150)

![Screenshot 2019-05-28 at 13 30 30](https://user-images.githubusercontent.com/3767697/58474924-c7bc1300-814c-11e9-93dd-9e262da39499.png)

Please also note that 250 is currently our maxReplicas limit so I wonder what values would have been picked without this limit.

Two problems arise from this unbounded and broken traffic switch:
- Slow traffic switch (~ 10 mins) due to the high number of pods waiting to be ready - in this case, functionality was not totally broken so it was okay-ish but with a real production issue, it is unacceptable to have to wait for very long time due to incorrect prescaling
- Downstream services suffer because all these new pods initiate new connections

**Comment by aermakov-zalando** [comment]
This was fixed in a number of PRs in both stackset controller and kube-metrics-adapter. Please reopen if you see this happening again.
