### ISSUE TITLE
"Force" delete Stack objects 

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/stackset-controller#2]
`kubectl delete stack <foo>` seems to hang and never deletes the stack.

This seems to be by design due to the `finalizer`. Let's deal with it later.

**Comment by mikkeloscar** [comment]
This is intended to ensure you don't delete stacks which are getting traffic. There is one edge case where you can't delete the last stack when it's the only one getting traffic, maybe we need to allow "force" deleting of the stack if it's desired.

**Comment by mikkeloscar** [comment]
"Fixed" in #32
