### ISSUE TITLE
dev environment does not deploy the right image

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/stackset-controller#25]
% kubectl logs stackset-controller-56449647cf-rtjt8
Error from server (BadRequest): container "stackset-controller" in pod "stackset-controller-56449647cf-rtjt8" is waiting to start: trying and failing to pull image
zsh: exit 1     kubectl logs stackset-controller-56449647cf-rtjt8

But delivery.yaml builds IMAGE=registry-write.opensource.zalan.do/teapot/stackset-controller-test with "-test"

**Comment by linki** [comment]
@szuecs I supposed this has been fixed in https://github.bus.zalan.do/automata/stackset-controller-deploy/pull/5

Reopen if not.
