### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/stackset-controller#34]
We don't have many tests yet. Since [stackset-controller](https://github.com/zalando-incubator/stackset-controller) is now in production, we might receive feature requests /bug reports, adding tests will help us deliver these more quickly. As we make the code more "testable", this might also improve the quality.

**Comment by szuecs** [comment]
46% is already good progress, we should reach  60% to close this

**Comment by mikkeloscar** [comment]
We are at `78%` :D Closing this!
