### ISSUE TITLE
Routegroup Algorithm Support

### ISSUE THREAD

**Issue by herojan** [zalando-incubator/stackset-controller#340]
Right now, I don't believe there is a way to specify the load balancer algorithm to be used for the generated default backends in a route group.

i.e. https://github.com/zalando-incubator/stackset-controller/blob/master/pkg/core/stackset.go#L168 uses the default algorithm.

I would like to be able to say for the default backend to use consistenthash load balancer, for example.

**Comment by herojan** [comment]
@mikkeloscar @szuecs Does this feature request make sense? I made a pr for it anyway which I think works.

**Comment by mikkeloscar** [comment]
I think it does make sense. Seems like we forgot/didn't consider this use case when we first added support. I'll take a closer look at your PR a bit later today.
