### ISSUE TITLE
Deleting stackset does not delete deployment or stacks

### ISSUE THREAD

**Issue by juhmelo** [zalando-incubator/stackset-controller#46]
I tried retiring my test application in `stups-test` by deleting my stackset:
```
$ zk delete stackset my-app-jylipoti
stackset.zalando.org "my-app-jylipoti" deleted
```
However the delete did not cascade to other resources, i.e. stack `my-app-jylipoti-pr-1-1` is still present and so is deployment `my-app-jylipoti-pr-1-1`.

**Comment by mikkeloscar** [comment]
I think this is because your stackset was created before we fixed the issue in the controller. It works a bit differently since: https://github.com/zalando-incubator/stackset-controller/pull/32

Migration from the old behavior was not implemented. I cleaned up your stack.
