### ISSUE TITLE
Define a cleaner format to interact with the HPA in the stackset controller

### ISSUE THREAD

**Issue by muaazsaleem** [zalando-incubator/stackset-controller#62]
At the moment the stackset-controller just supports [Horizontal Pod Autoscaler Spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#horizontalpodautoscaler-v2beta1-autoscaling) under the `horizontalPodAutoscaler ` key as is. Therefore, users also have the responsibility to put sensible defaults. The format can also get particularly messy when configuring [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) using [custom metrics](https://github.com/mikkeloscar/kube-metrics-adapter/).

It might make sense for us to provide a more minimalistic key e.g `Autoscaler` with sensible defaults and a cleaner way to provide customer scaling metrics.

**Comment by arjunrn** [comment]
To add to this there is a replica field in the deployment definition and there is a `minReplicas` and `maxReplicas` field in the HPA definition. This is somewhat ambiguous.

**Comment by arjunrn** [comment]
Discussion on the format for the HPA integration is happening [here](https://github.bus.zalan.do/teapot/issues/issues/1375).

**Comment by mikkeloscar** [comment]
This was done and is documented here: https://github.com/zalando-incubator/stackset-controller/blob/master/docs/howtos.md#specifying-horizontal-pod-autoscaler
