### ISSUE TITLE
Forbid setting stack lifecycle limit to 1 or support it properly

### ISSUE THREAD

**Issue by aermakov-zalando** [zalando-incubator/stackset-controller#88]
Setting stackLifecycle.limit to 1 causes the stackset controller to constantly delete the newly created stack in GC (because it doesn't have traffic) and then recreate it on the next iteration. This should either work correctly as a special case or be disallowed by validation.

**Comment by mikkeloscar** [comment]
This was changed to mean: "number of stacks without traffic to keep around". The validation checks for `minimum: 1`
